module.exports = [
{ type: 'spade', value: 1 },
{ type: 'spade', value: 2 },
{ type: 'spade', value: 3 },
{ type: 'spade', value: 4 },
{ type: 'spade', value: 5 },
{ type: 'spade', value: 6 },
{ type: 'spade', value: 7 },
{ type: 'spade', value: 8 },
{ type: 'spade', value: 9 },
{ type: 'spade', value: 10 },
{ type: 'spade', value: 11 },
{ type: 'spade', value: 12 },
{ type: 'spade', value: 13 },

{ type: 'diamond', value: 1 },
{ type: 'diamond', value: 2 },
{ type: 'diamond', value: 3 },
{ type: 'diamond', value: 4 },
{ type: 'diamond', value: 5 },
{ type: 'diamond', value: 6 },
{ type: 'diamond', value: 7 },
{ type: 'diamond', value: 8 },
{ type: 'diamond', value: 9 },
{ type: 'diamond', value: 10 },
{ type: 'diamond', value: 11 },
{ type: 'diamond', value: 12 },
{ type: 'diamond', value: 13 },

{ type: 'heart', value: 1 },
{ type: 'heart', value: 2 },
{ type: 'heart', value: 3 },
{ type: 'heart', value: 4 },
{ type: 'heart', value: 5 },
{ type: 'heart', value: 6 },
{ type: 'heart', value: 7 },
{ type: 'heart', value: 8 },
{ type: 'heart', value: 9 },
{ type: 'heart', value: 10 },
{ type: 'heart', value: 11 },
{ type: 'heart', value: 12 },
{ type: 'heart', value: 13 },

{ type: 'club', value: 1 },
{ type: 'club', value: 2 },
{ type: 'club', value: 3 },
{ type: 'club', value: 4 },
{ type: 'club', value: 5 },
{ type: 'club', value: 6 },
{ type: 'club', value: 7 },
{ type: 'club', value: 8 },
{ type: 'club', value: 9 },
{ type: 'club', value: 10 },
{ type: 'club', value: 11 },
{ type: 'club', value: 12 },
{ type: 'club', value: 13 },
]